{ pkgs, config, lib, ... }:

{
  # Only manage the ~/.zshrc file
  # We do NOT enable 'programs.zsh' which would install the binary
  home.file.".zshrc".text = ''
    # ~/.zshrc generated by Home Manager script
    # Simple ZSH config that auto-attaches to tmux on SSH login
    
    # Enable completions if available
    autoload -Uz compinit && compinit
    
    # Minimal prompt
    PS1="%n@%m %1~ %# "
    
    # Basic aliases
    alias ls='ls -G'
    alias ll='ls -lG'
    alias l='ls -lahG'
    
    # Use Home Manager installed binaries
    export PATH="$HOME/.local/bin:$HOME/.nix-profile/bin:/run/current-system/sw/bin${lib.concatMapStrings (path: ":${path}") config.home.sessionPath}:$PATH"
    
    # Use Home Manager session variables
    ${lib.concatStrings (lib.mapAttrsToList (name: value: ''
    export ${name}="${toString value}"
    '') config.home.sessionVariables)}
    
    # Auto-start tmux for SSH connections
    if [[ -z "$TMUX" && -n "$SSH_CONNECTION" ]]; then
        # Ensure external drives are mounted
        if command -v diskutil >/dev/null 2>&1; then
            # Attempt to mount by volume name (safer than disk identifiers)
            diskutil mount "portable" >/dev/null 2>&1 || true
            diskutil mount "realme" >/dev/null 2>&1 || true
        fi
        
        # Start media server in detached tmux session if not running
        MEDIA_SERVER_DIR="/Volumes/realme/Dev/media"
        if [[ -d "$MEDIA_SERVER_DIR" && -x "$MEDIA_SERVER_DIR/server" ]]; then
            if ! ${pkgs.tmux}/bin/tmux has-session -t "background" 2>/dev/null; then
                cd "$MEDIA_SERVER_DIR" && ${pkgs.tmux}/bin/tmux new-session -d -s "background" "./server"
            fi
        fi

        if command -v tmux >/dev/null 2>&1; then
            exec tmux new-session -A -s 0
        fi
    fi
  '';
}
