{ pkgs, ... }:

{
  # Create the WebDAV start script
  home.file.".local/bin/start-webdav-tmux" = {
    text = ''
      #!/usr/bin/env bash
      # Start WebDAV server in a detached tmux SESSION named 'webdav'
      # This runs on the SAME tmux server as your main session, just isolated.

      SESSION_NAME="webdav"
      MOUNT_POINT="/Volumes/portable"
      PORT="6969"
      USER="steven"
      HTPASSWD_FILE="$HOME/.config/rclone/htpasswd"

      # Ensure config directory exists
      mkdir -p "$HOME/.config/rclone"

      # Check if htpasswd file exists, if not, create it
      if [ ! -f "$HTPASSWD_FILE" ]; then
          echo "Creating WebDAV password file..."
          read -s -p "Enter password for WebDAV user '$USER': " PASS
          echo ""
          ${pkgs.apacheHttpd}/bin/htpasswd -cb "$HTPASSWD_FILE" "$USER" "$PASS"
          echo "Password set."
      fi

      # Ensure the mount point exists
      if [ ! -d "$MOUNT_POINT" ]; then
          echo "Warning: $MOUNT_POINT does not exist!"
          echo "Please mount your drive or create the directory."
          exit 1
      fi

      # Check if session already exists
      if ${pkgs.tmux}/bin/tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
          exit 0
      fi

      # Start new session
      ${pkgs.tmux}/bin/tmux new-session -d -s "$SESSION_NAME" \
          "${pkgs.rclone}/bin/rclone serve webdav '$MOUNT_POINT' --addr 0.0.0.0:$PORT --htpasswd '$HTPASSWD_FILE' --vfs-cache-mode writes; read"
    '';
    executable = true;
  };

  # Only manage the ~/.zshrc file
  # We do NOT enable 'programs.zsh' which would install the binary
  home.file.".zshrc".text = ''
    # ~/.zshrc generated by Home Manager script
    # Simple ZSH config that auto-attaches to tmux on SSH login
    
    # Enable completions if available
    autoload -Uz compinit && compinit
    
    # Minimal prompt
    PS1="%n@%m %1~ %# "
    
    # Basic aliases
    alias ls='ls -G'
    alias ll='ls -lG'
    alias l='ls -lahG'
    
    # Use Home Manager installed binaries
    export PATH="$HOME/.local/bin:$HOME/.nix-profile/bin:/run/current-system/sw/bin:$PATH"
    
    # Auto-start tmux for SSH connections
    if [[ -z "$TMUX" && -n "$SSH_CONNECTION" ]]; then
        # Ensure external drives are mounted
        if command -v diskutil >/dev/null 2>&1; then
            # Attempt to mount by volume name (safer than disk identifiers)
            diskutil mount "portable" >/dev/null 2>&1 || true
            diskutil mount "realme" >/dev/null 2>&1 || true
        fi
        
        # Start WebDAV server in detached tmux session if not running
        if [[ -f "$HOME/.local/bin/start-webdav-tmux" ]]; then
            "$HOME/.local/bin/start-webdav-tmux" >/dev/null 2>&1 &
        fi

        if command -v tmux >/dev/null 2>&1; then
            exec tmux new-session -A -s 0
        fi
    fi
  '';
}
